const express = require('express');
const connectDB = require('./database/db');
const cors = require('cors');
const morgan = require('morgan');
const dotenv=require('dotenv').config();
const authRoutes = require('./routes/auth');
const app = express();
app.use(cors());
app.use(morgan('dev'));
app.use(express.json());
// app.use(express.urlencoded({extended: true}));
app.use('/api/auth',authRoutes);
connectDB();
const PORT = process.env.APP_PORT;
app.listen(PORT,()=>console.log(`Server is running on http://localhost:${PORT}`));